name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run AI Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use Secret Here
        run: |
          curl -X POST "http://localhost:8000/review" \
          -H "Content-Type: application/json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"repo": "${{ github.repository }}", "pr": "${{ github.event.pull_request.number }}"}'
